# Generated by Django 3.2.6 on 2021-08-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_protected_acc',
            field=models.BooleanField(default=False),
        ),
    ]
